---
pagetitle: "Sailing the Macro Workshop 2024"
page-layout: custom
section-divs: false
toc: false
css: index.css
description: |
  5th Sailing the Macro Workshop - Ortigia, Siracusa, Italy
resources:
  - sailingthemacrocall.pdf
editor: 
    render-on-save: true
---




::: {.content-block}

::: {.hero-text}
# 5th Sailing the Macro Workshop

### September 5-7, Ortigia, Siracusa, Italy

We are pleased to announce that the fifth edition of the Sailing the Macro Workshop will be held at the Ortygia Foundation in Ortygia, Siracusa, Italy. 

We invite submissions from researchers, academics, and practitioners for original research papers covering various macroeconomics topics. The workshop aims to facilitate discussions of ongoing research on policy-relevant questions and provide a platform for exchanging ideas and findings among experts in the field.

The [Econometrics Journal]{style="font-color: #822433"} will feature a special issue on "Macroeconometric Policy Analysis." Conference participants whose papers align with this theme will have the opportunity to submit their work for consideration in this special issue (see below for submission guidelines).

::: {.keynote}
### [Keynote speakers]{.redsap}

  - Refet Gürkaynak (_Bilkent University_)
  - Sophocles Mavroeidis (_University of Oxford_)
  - Geert Mesters (_Universitat Pompeu Fabra_)
:::

## Conference Topics

The workshop welcomes submissions across the full spectrum of macroeconomics research. Topics include, but are not limited to:

- Macroeconomic theory and modeling
- Monetary and fiscal policy analysis
- International macroeconomics and open economy models
- Labor markets and unemployment dynamics
- Growth theory and economic development
- Financial market interactions with the real economy
- Climate change and macroeconomic implications
- Distributional aspects of macroeconomic policies
- Macroeconometric tools and methods relevant for policy analysis

Given the upcoming #text(fill: redsap)[Econometrics Journal] special issue, we particularly encourage submissions focusing on innovative macroeconometric methods, empirical policy evaluation techniques, and quantitative frameworks for analyzing macroeconomic policies.


## Conference Submission Guidelines

We invite authors to submit their original, unpublished research papers to be considered for presentation at the conference.

Please submit your paper using the submission [form](https://). 

::: {.callout-important}
**Deadline:** [by 12 CET on 05 May 2024]{.redsap}

**Acceptance notification:** Authors will be notified of the acceptance by the end of May 2025.

:::

## Econometrics Journal Special Issue


The [Econometrics Journal]{.redsap} will publish a Special Issue on the topic [_Macroeconometric Policy Analysis_]{.redsap}, edited by [Raffaella Giacomini](https://raffaellagiacomini.wixsite.com/research) (UCL) in collaboration with [Daniel Lewis](https://sites.google.com/view/danjlewis/home) (UCL). We are encouraging submissions on this topic to [both]{.red} the conference and the journal special issue.

Submissions to the special issue should follow the journal guidelines at 

<https://res.org.uk/submissions>

Authors should select "Special Issue Article: MACROPOLICY" as the "category of submission" in Step 2 of the submission procedure. 


::: {.callout-important}
Authors who intend to submit their papers for the special issue should mark the approapriate field in the conference submission form. 
:::



:::


:::







::: {.content-block}
::: {.features}


::: {.feature}
### PhD Students
The conference organizing committee is committed to supporting and nurturing the next generation of macroeconomic researchers. As such, we highly encourage Ph.D. students to submit their research papers for presentation at the conference.

Ph.D. students will have the opportunity to present their work to a distinguished audience of experts in the field, receive valuable feedback on their research, and establish connections with leading academics and practitioners.

<!-- ::: {.learn-more}
[Learn more »](docs/output-formats/all-formats.qmd)
::: -->
:::

::: {.feature}
### Conference Venue
The conference will be held at the [Ortygia Foundation]("https://www.ortygiabs.org/en"), located in the heart of Ortygia, Siracusa, Italy.

The Foundation offers an inspiring and unique setting for intellectual exchange and debate, fostering collaboration and networking among participants.

<!-- ::: {.learn-more}
[Learn more »](information.qmd)
::: -->
:::

::: {.feature}
### Sailing the Macro
As it is now tradition with the Sailing the Macro workshop, the afternoons will be dedicated to sailing. 

<!-- Conference participants can join sailing courses organized by [Magister Marine](https://www.facebook.com/MagisterMarine/). -->

<!-- ::: {.learn-more}
[Learn more »](docs/tools/jupyter-lab.qmd)
::: -->
:::

::: {.feature}
### Conference Fees
To partially cover conference costs, a registration fee of 200 Euros is applicable for all participants, with a discounted fee of 100 Euros for Ph.D. students.

The conference fee includes access to all conference sessions, conference materials, coffee breaks, lunches, and a conference dinner. Please note that accommodation and travel expenses are not included in the conference fee and must be arranged by the participants.


<!-- ::: {.learn-more}
[Learn more »](docs/interactive/)
::: -->
:::

::: {.feature}
### Scientific & Organizing Committee

- Elton Beqiraj (Sapienza University)
- Cristiano Cantore (Sapienza University)
- Marco Di Pietro (Sapienza University)
- Francesco Lucidi (Sapienza University)
- Salvatore Nisticò (Sapienza University)
- Valeria Patella (Sapienza University)
- Marta Maria Pisa (Sapienza University)
- Giuseppe Ragusa (Sapienza University)
- Massimiliano Tancioni (Sapienza University)



:::

:::
:::


